// Generated by gencpp from file collect_node/TwoInts.msg
// DO NOT EDIT!


#ifndef COLLECT_NODE_MESSAGE_TWOINTS_H
#define COLLECT_NODE_MESSAGE_TWOINTS_H

#include <ros/service_traits.h>


#include <collect_node/TwoIntsRequest.h>
#include <collect_node/TwoIntsResponse.h>


namespace collect_node
{

struct TwoInts
{

typedef TwoIntsRequest Request;
typedef TwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TwoInts
} // namespace collect_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::collect_node::TwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::collect_node::TwoInts&) { return value(); }
};

template<>
struct DataType< ::collect_node::TwoInts > {
  static const char* value()
  {
    return "collect_node/TwoInts";
  }

  static const char* value(const ::collect_node::TwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::collect_node::TwoIntsRequest> should match
// service_traits::MD5Sum< ::collect_node::TwoInts >
template<>
struct MD5Sum< ::collect_node::TwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::collect_node::TwoInts >::value();
  }
  static const char* value(const ::collect_node::TwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::collect_node::TwoIntsRequest> should match
// service_traits::DataType< ::collect_node::TwoInts >
template<>
struct DataType< ::collect_node::TwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::collect_node::TwoInts >::value();
  }
  static const char* value(const ::collect_node::TwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::collect_node::TwoIntsResponse> should match
// service_traits::MD5Sum< ::collect_node::TwoInts >
template<>
struct MD5Sum< ::collect_node::TwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::collect_node::TwoInts >::value();
  }
  static const char* value(const ::collect_node::TwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::collect_node::TwoIntsResponse> should match
// service_traits::DataType< ::collect_node::TwoInts >
template<>
struct DataType< ::collect_node::TwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::collect_node::TwoInts >::value();
  }
  static const char* value(const ::collect_node::TwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLLECT_NODE_MESSAGE_TWOINTS_H
