uint8 outwater_status         # 出水, 状态：[0x00] passed；[0x01] failed
uint8 recharge_hall_status    # 回充hall, 状态：[0x00] passed；[0x01] failed
uint8 dirtybox_hall_status    # 滤篮hall, 状态：[0x00] passed；[0x01] failed
uint8 turn_motor_hall_status  # 转向电机hall,状态：[0x00] passed；[0x01] failed
uint8 dtof_status             # tof, 状态：[0x00] passed；[0x01] failed
uint8 ango_status             # 岸歌, 状态：[0x00] passed；[0x01] failed