// Generated by gencpp from file hj_interface/airBagControlResponse.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_AIRBAGCONTROLRESPONSE_H
#define HJ_INTERFACE_MESSAGE_AIRBAGCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct airBagControlResponse_
{
  typedef airBagControlResponse_<ContainerAllocator> Type;

  airBagControlResponse_()
    : result(0)
    , status(0)  {
    }
  airBagControlResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;

   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::hj_interface::airBagControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::airBagControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct airBagControlResponse_

typedef ::hj_interface::airBagControlResponse_<std::allocator<void> > airBagControlResponse;

typedef boost::shared_ptr< ::hj_interface::airBagControlResponse > airBagControlResponsePtr;
typedef boost::shared_ptr< ::hj_interface::airBagControlResponse const> airBagControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::airBagControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::airBagControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::airBagControlResponse_<ContainerAllocator1> & lhs, const ::hj_interface::airBagControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::airBagControlResponse_<ContainerAllocator1> & lhs, const ::hj_interface::airBagControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::airBagControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::airBagControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::airBagControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::airBagControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::airBagControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::airBagControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::airBagControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "012e1c02f272e361be1e6464b1a49318";
  }

  static const char* value(const ::hj_interface::airBagControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x012e1c02f272e361ULL;
  static const uint64_t static_value2 = 0xbe1e6464b1a49318ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::airBagControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/airBagControlResponse";
  }

  static const char* value(const ::hj_interface::airBagControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::airBagControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 result # 0 成功 -1 失败\n"
"uint8 status # 1 充气中 2 放气中 3 充气结束 4 放气结束\n"
;
  }

  static const char* value(const ::hj_interface::airBagControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::airBagControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct airBagControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::airBagControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::airBagControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_AIRBAGCONTROLRESPONSE_H
