// Generated by gencpp from file hj_interface/AlgWorkResult.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_ALGWORKRESULT_H
#define HJ_INTERFACE_MESSAGE_ALGWORKRESULT_H

#include <ros/service_traits.h>


#include <hj_interface/AlgWorkResultRequest.h>
#include <hj_interface/AlgWorkResultResponse.h>


namespace hj_interface
{

struct AlgWorkResult
{

typedef AlgWorkResultRequest Request;
typedef AlgWorkResultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AlgWorkResult
} // namespace hj_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hj_interface::AlgWorkResult > {
  static const char* value()
  {
    return "ac09fb0b21e284005fbd911853414070";
  }

  static const char* value(const ::hj_interface::AlgWorkResult&) { return value(); }
};

template<>
struct DataType< ::hj_interface::AlgWorkResult > {
  static const char* value()
  {
    return "hj_interface/AlgWorkResult";
  }

  static const char* value(const ::hj_interface::AlgWorkResult&) { return value(); }
};


// service_traits::MD5Sum< ::hj_interface::AlgWorkResultRequest> should match
// service_traits::MD5Sum< ::hj_interface::AlgWorkResult >
template<>
struct MD5Sum< ::hj_interface::AlgWorkResultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hj_interface::AlgWorkResult >::value();
  }
  static const char* value(const ::hj_interface::AlgWorkResultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hj_interface::AlgWorkResultRequest> should match
// service_traits::DataType< ::hj_interface::AlgWorkResult >
template<>
struct DataType< ::hj_interface::AlgWorkResultRequest>
{
  static const char* value()
  {
    return DataType< ::hj_interface::AlgWorkResult >::value();
  }
  static const char* value(const ::hj_interface::AlgWorkResultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hj_interface::AlgWorkResultResponse> should match
// service_traits::MD5Sum< ::hj_interface::AlgWorkResult >
template<>
struct MD5Sum< ::hj_interface::AlgWorkResultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hj_interface::AlgWorkResult >::value();
  }
  static const char* value(const ::hj_interface::AlgWorkResultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hj_interface::AlgWorkResultResponse> should match
// service_traits::DataType< ::hj_interface::AlgWorkResult >
template<>
struct DataType< ::hj_interface::AlgWorkResultResponse>
{
  static const char* value()
  {
    return DataType< ::hj_interface::AlgWorkResult >::value();
  }
  static const char* value(const ::hj_interface::AlgWorkResultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_ALGWORKRESULT_H
