// Generated by gencpp from file hj_interface/BigDataSave.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_BIGDATASAVE_H
#define HJ_INTERFACE_MESSAGE_BIGDATASAVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct BigDataSave_
{
  typedef BigDataSave_<ContainerAllocator> Type;

  BigDataSave_()
    : key()
    , payload()
    , cmd(0)  {
    }
  BigDataSave_(const ContainerAllocator& _alloc)
    : key(_alloc)
    , payload(_alloc)
    , cmd(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _key_type;
  _key_type key;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _payload_type;
  _payload_type payload;

   typedef uint8_t _cmd_type;
  _cmd_type cmd;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(kBigdataImmediate)
  #undef kBigdataImmediate
#endif
#if defined(_WIN32) && defined(kBigdataWait)
  #undef kBigdataWait
#endif

  enum {
    kBigdataImmediate = 1u,
    kBigdataWait = 2u,
  };


  typedef boost::shared_ptr< ::hj_interface::BigDataSave_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::BigDataSave_<ContainerAllocator> const> ConstPtr;

}; // struct BigDataSave_

typedef ::hj_interface::BigDataSave_<std::allocator<void> > BigDataSave;

typedef boost::shared_ptr< ::hj_interface::BigDataSave > BigDataSavePtr;
typedef boost::shared_ptr< ::hj_interface::BigDataSave const> BigDataSaveConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::BigDataSave_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::BigDataSave_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::BigDataSave_<ContainerAllocator1> & lhs, const ::hj_interface::BigDataSave_<ContainerAllocator2> & rhs)
{
  return lhs.key == rhs.key &&
    lhs.payload == rhs.payload &&
    lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::BigDataSave_<ContainerAllocator1> & lhs, const ::hj_interface::BigDataSave_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::BigDataSave_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::BigDataSave_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::BigDataSave_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::BigDataSave_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::BigDataSave_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::BigDataSave_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::BigDataSave_<ContainerAllocator> >
{
  static const char* value()
  {
    return "786e4c4402bf077860ca7985950bda36";
  }

  static const char* value(const ::hj_interface::BigDataSave_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x786e4c4402bf0778ULL;
  static const uint64_t static_value2 = 0x60ca7985950bda36ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::BigDataSave_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/BigDataSave";
  }

  static const char* value(const ::hj_interface::BigDataSave_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::BigDataSave_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string key\n"
"string payload\n"
"uint8 cmd\n"
"uint8      kBigdataImmediate = 1\n"
"uint8      kBigdataWait  = 2\n"
"\n"
;
  }

  static const char* value(const ::hj_interface::BigDataSave_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::BigDataSave_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
      stream.next(m.payload);
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BigDataSave_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::BigDataSave_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::BigDataSave_<ContainerAllocator>& v)
  {
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.key);
    s << indent << "payload: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.payload);
    s << indent << "cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_BIGDATASAVE_H
