// Generated by gencpp from file hj_interface/Chat.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_CHAT_H
#define HJ_INTERFACE_MESSAGE_CHAT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct Chat_
{
  typedef Chat_<ContainerAllocator> Type;

  Chat_()
    : start_circle(false)
    , match_complete(false)  {
    }
  Chat_(const ContainerAllocator& _alloc)
    : start_circle(false)
    , match_complete(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_circle_type;
  _start_circle_type start_circle;

   typedef uint8_t _match_complete_type;
  _match_complete_type match_complete;





  typedef boost::shared_ptr< ::hj_interface::Chat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::Chat_<ContainerAllocator> const> ConstPtr;

}; // struct Chat_

typedef ::hj_interface::Chat_<std::allocator<void> > Chat;

typedef boost::shared_ptr< ::hj_interface::Chat > ChatPtr;
typedef boost::shared_ptr< ::hj_interface::Chat const> ChatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::Chat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::Chat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::Chat_<ContainerAllocator1> & lhs, const ::hj_interface::Chat_<ContainerAllocator2> & rhs)
{
  return lhs.start_circle == rhs.start_circle &&
    lhs.match_complete == rhs.match_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::Chat_<ContainerAllocator1> & lhs, const ::hj_interface::Chat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::Chat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::Chat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::Chat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::Chat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::Chat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::Chat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::Chat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6524a440895641d7c3deafdc307c6d9";
  }

  static const char* value(const ::hj_interface::Chat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6524a440895641dULL;
  static const uint64_t static_value2 = 0x7c3deafdc307c6d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::Chat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/Chat";
  }

  static const char* value(const ::hj_interface::Chat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::Chat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start_circle\n"
"bool match_complete\n"
;
  }

  static const char* value(const ::hj_interface::Chat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::Chat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_circle);
      stream.next(m.match_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Chat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::Chat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::Chat_<ContainerAllocator>& v)
  {
    s << indent << "start_circle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_circle);
    s << indent << "match_complete: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.match_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_CHAT_H
