// Generated by gencpp from file hj_interface/FileUpload.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_FILEUPLOAD_H
#define HJ_INTERFACE_MESSAGE_FILEUPLOAD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct FileUpload_
{
  typedef FileUpload_<ContainerAllocator> Type;

  FileUpload_()
    : type(0)
    , deleteOnSuccess(false)
    , filePath()
    , logId(0)  {
    }
  FileUpload_(const ContainerAllocator& _alloc)
    : type(0)
    , deleteOnSuccess(false)
    , filePath(_alloc)
    , logId(0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;

   typedef uint8_t _deleteOnSuccess_type;
  _deleteOnSuccess_type deleteOnSuccess;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _filePath_type;
  _filePath_type filePath;

   typedef uint64_t _logId_type;
  _logId_type logId;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MAP)
  #undef MAP
#endif
#if defined(_WIN32) && defined(TRACE)
  #undef TRACE
#endif
#if defined(_WIN32) && defined(CLEANRESULT)
  #undef CLEANRESULT
#endif
#if defined(_WIN32) && defined(DEVICELOG)
  #undef DEVICELOG
#endif
#if defined(_WIN32) && defined(BURYPOINT)
  #undef BURYPOINT
#endif

  enum {
    MAP = 0u,
    TRACE = 1u,
    CLEANRESULT = 2u,
    DEVICELOG = 3u,
    BURYPOINT = 4u,
  };


  typedef boost::shared_ptr< ::hj_interface::FileUpload_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::FileUpload_<ContainerAllocator> const> ConstPtr;

}; // struct FileUpload_

typedef ::hj_interface::FileUpload_<std::allocator<void> > FileUpload;

typedef boost::shared_ptr< ::hj_interface::FileUpload > FileUploadPtr;
typedef boost::shared_ptr< ::hj_interface::FileUpload const> FileUploadConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::FileUpload_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::FileUpload_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::FileUpload_<ContainerAllocator1> & lhs, const ::hj_interface::FileUpload_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.deleteOnSuccess == rhs.deleteOnSuccess &&
    lhs.filePath == rhs.filePath &&
    lhs.logId == rhs.logId;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::FileUpload_<ContainerAllocator1> & lhs, const ::hj_interface::FileUpload_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::FileUpload_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::FileUpload_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::FileUpload_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::FileUpload_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::FileUpload_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::FileUpload_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::FileUpload_<ContainerAllocator> >
{
  static const char* value()
  {
    return "705cff8ed183206f5f1b779645519722";
  }

  static const char* value(const ::hj_interface::FileUpload_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x705cff8ed183206fULL;
  static const uint64_t static_value2 = 0x5f1b779645519722ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::FileUpload_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/FileUpload";
  }

  static const char* value(const ::hj_interface::FileUpload_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::FileUpload_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8  MAP  = 0\n"
"uint8  TRACE = 1\n"
"uint8  CLEANRESULT = 2\n"
"uint8  DEVICELOG = 3\n"
"uint8  BURYPOINT = 4\n"
"uint8  type\n"
"bool  deleteOnSuccess\n"
"string filePath\n"
"uint64 logId\n"
;
  }

  static const char* value(const ::hj_interface::FileUpload_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::FileUpload_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.deleteOnSuccess);
      stream.next(m.filePath);
      stream.next(m.logId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FileUpload_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::FileUpload_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::FileUpload_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "deleteOnSuccess: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.deleteOnSuccess);
    s << indent << "filePath: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.filePath);
    s << indent << "logId: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.logId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_FILEUPLOAD_H
