uint8 action_cmd    # 1: slam建图 2: slam重定位
                    # 11: 清扫水面 12: 池底清扫 13: 池壁清扫
                    # 18: 姿态调整
                    # 19: 清洁模式
                    # 21: 召回 22: 回充
                    # 31: slam状态请求 32: navi状态请求 35: 获取清扫记录
                    # 103: slam停止建图 104: slam停止定位
                    # 105：navi停止建图/重定位延边 106：navi停止极限延边
                    # 111: 暂停清扫 112: 继续清扫 113: 停止清扫
                    # 123: 停止召回 124: 停止回充
---

uint8 result                # 0: 收到 
                            # 1: slam待机 2: slam建图中 3: slam定位中 
CleanRecord CleanRecord     # 清扫记录