# set(G2O_DIR /usr/local/lib/cmake/g2o)
find_package(G2O REQUIRED)
include_directories(${G2O_INCLUDE_DIR})
message(STATUS "G2O_INCLUDE_DIR: ${G2O_INCLUDE_DIR}")
message(STATUS "G2O_FOUND: ${G2O_FOUND}")
SET(G2O_LIBRARIES ${G2O_STUFF_LIBRARY} ${G2O_CORE_LIBRARY} ${G2O_SOLVER_CSPARSE} ${G2O_SOLVER_CSPARSE_EXTENSION} 
${G2O_SOLVER_DENSE} ${G2O_TYPES_SBA})
message(STATUS "G2O_LIBRARIES: ${G2O_LIBRARIES}")