uint8 action_cmd    # 11: 清扫水面 12: 池底清扫 13: 池壁清扫
                    # 19: 清洁模式
                    # 21: 召回 22: 回充
                    # 32: navi状态请求
                    # 111: 暂停清扫 112: 继续清扫 113: 停止清扫
                    # 123: 停止召回 124: 停止回充
                    
uint8 clean_mode    # 1: 变频清洁 2: 标准清洁 3: 深度清洁
uint8 clean_method  # 1: 随机清扫 2: 十字弓清扫

---

uint8 result   # 0: 收到 
               # 11: navi待机 12: navi清扫中
               # 21: navi召回中 22: navi回充中