// Generated by gencpp from file hj_interface/MagCalibAction.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_MAGCALIBACTION_H
#define HJ_INTERFACE_MESSAGE_MAGCALIBACTION_H

#include <ros/service_traits.h>


#include <hj_interface/MagCalibActionRequest.h>
#include <hj_interface/MagCalibActionResponse.h>


namespace hj_interface
{

struct MagCalibAction
{

typedef MagCalibActionRequest Request;
typedef MagCalibActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MagCalibAction
} // namespace hj_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hj_interface::MagCalibAction > {
  static const char* value()
  {
    return "4bf7001cf372c163e152ddf2c2566da6";
  }

  static const char* value(const ::hj_interface::MagCalibAction&) { return value(); }
};

template<>
struct DataType< ::hj_interface::MagCalibAction > {
  static const char* value()
  {
    return "hj_interface/MagCalibAction";
  }

  static const char* value(const ::hj_interface::MagCalibAction&) { return value(); }
};


// service_traits::MD5Sum< ::hj_interface::MagCalibActionRequest> should match
// service_traits::MD5Sum< ::hj_interface::MagCalibAction >
template<>
struct MD5Sum< ::hj_interface::MagCalibActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hj_interface::MagCalibAction >::value();
  }
  static const char* value(const ::hj_interface::MagCalibActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hj_interface::MagCalibActionRequest> should match
// service_traits::DataType< ::hj_interface::MagCalibAction >
template<>
struct DataType< ::hj_interface::MagCalibActionRequest>
{
  static const char* value()
  {
    return DataType< ::hj_interface::MagCalibAction >::value();
  }
  static const char* value(const ::hj_interface::MagCalibActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hj_interface::MagCalibActionResponse> should match
// service_traits::MD5Sum< ::hj_interface::MagCalibAction >
template<>
struct MD5Sum< ::hj_interface::MagCalibActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hj_interface::MagCalibAction >::value();
  }
  static const char* value(const ::hj_interface::MagCalibActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hj_interface::MagCalibActionResponse> should match
// service_traits::DataType< ::hj_interface::MagCalibAction >
template<>
struct DataType< ::hj_interface::MagCalibActionResponse>
{
  static const char* value()
  {
    return DataType< ::hj_interface::MagCalibAction >::value();
  }
  static const char* value(const ::hj_interface::MagCalibActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_MAGCALIBACTION_H
