// Generated by gencpp from file hj_interface/NaviWheel.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_NAVIWHEEL_H
#define HJ_INTERFACE_MESSAGE_NAVIWHEEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct NaviWheel_
{
  typedef NaviWheel_<ContainerAllocator> Type;

  NaviWheel_()
    : timestamp()
    , left_wheel(0)
    , right_wheel(0)  {
    }
  NaviWheel_(const ContainerAllocator& _alloc)
    : timestamp()
    , left_wheel(0)
    , right_wheel(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef int16_t _left_wheel_type;
  _left_wheel_type left_wheel;

   typedef int16_t _right_wheel_type;
  _right_wheel_type right_wheel;





  typedef boost::shared_ptr< ::hj_interface::NaviWheel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::NaviWheel_<ContainerAllocator> const> ConstPtr;

}; // struct NaviWheel_

typedef ::hj_interface::NaviWheel_<std::allocator<void> > NaviWheel;

typedef boost::shared_ptr< ::hj_interface::NaviWheel > NaviWheelPtr;
typedef boost::shared_ptr< ::hj_interface::NaviWheel const> NaviWheelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::NaviWheel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::NaviWheel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::NaviWheel_<ContainerAllocator1> & lhs, const ::hj_interface::NaviWheel_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.left_wheel == rhs.left_wheel &&
    lhs.right_wheel == rhs.right_wheel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::NaviWheel_<ContainerAllocator1> & lhs, const ::hj_interface::NaviWheel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::NaviWheel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::NaviWheel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::NaviWheel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::NaviWheel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::NaviWheel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::NaviWheel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::NaviWheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "380645d5befdfd6fee27d39dc348a380";
  }

  static const char* value(const ::hj_interface::NaviWheel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x380645d5befdfd6fULL;
  static const uint64_t static_value2 = 0xee27d39dc348a380ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::NaviWheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/NaviWheel";
  }

  static const char* value(const ::hj_interface::NaviWheel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::NaviWheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp\n"
"int16 left_wheel #!< mm/s\n"
"int16 right_wheel\n"
;
  }

  static const char* value(const ::hj_interface::NaviWheel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::NaviWheel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.left_wheel);
      stream.next(m.right_wheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NaviWheel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::NaviWheel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::NaviWheel_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "left_wheel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left_wheel);
    s << indent << "right_wheel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right_wheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_NAVIWHEEL_H
