// Generated by gencpp from file hj_interface/SelfCleanMotor.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_SELFCLEANMOTOR_H
#define HJ_INTERFACE_MESSAGE_SELFCLEANMOTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct SelfCleanMotor_
{
  typedef SelfCleanMotor_<ContainerAllocator> Type;

  SelfCleanMotor_()
    : timestamp()
    , self_clean(0)  {
    }
  SelfCleanMotor_(const ContainerAllocator& _alloc)
    : timestamp()
    , self_clean(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _self_clean_type;
  _self_clean_type self_clean;





  typedef boost::shared_ptr< ::hj_interface::SelfCleanMotor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::SelfCleanMotor_<ContainerAllocator> const> ConstPtr;

}; // struct SelfCleanMotor_

typedef ::hj_interface::SelfCleanMotor_<std::allocator<void> > SelfCleanMotor;

typedef boost::shared_ptr< ::hj_interface::SelfCleanMotor > SelfCleanMotorPtr;
typedef boost::shared_ptr< ::hj_interface::SelfCleanMotor const> SelfCleanMotorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::SelfCleanMotor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::SelfCleanMotor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::SelfCleanMotor_<ContainerAllocator1> & lhs, const ::hj_interface::SelfCleanMotor_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.self_clean == rhs.self_clean;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::SelfCleanMotor_<ContainerAllocator1> & lhs, const ::hj_interface::SelfCleanMotor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::SelfCleanMotor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::SelfCleanMotor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::SelfCleanMotor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::SelfCleanMotor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::SelfCleanMotor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::SelfCleanMotor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::SelfCleanMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c419882b3fd184f8b90cc22de0dff20";
  }

  static const char* value(const ::hj_interface::SelfCleanMotor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c419882b3fd184fULL;
  static const uint64_t static_value2 = 0x8b90cc22de0dff20ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::SelfCleanMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/SelfCleanMotor";
  }

  static const char* value(const ::hj_interface::SelfCleanMotor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::SelfCleanMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp\n"
"uint8 self_clean       #!< 0 刹车； 1 运行； 自清洁电机,目前没有转速\n"
;
  }

  static const char* value(const ::hj_interface::SelfCleanMotor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::SelfCleanMotor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.self_clean);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SelfCleanMotor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::SelfCleanMotor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::SelfCleanMotor_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "self_clean: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.self_clean);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_SELFCLEANMOTOR_H
