// Generated by gencpp from file hj_interface/SlamActionResponse.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_SLAMACTIONRESPONSE_H
#define HJ_INTERFACE_MESSAGE_SLAMACTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct SlamActionResponse_
{
  typedef SlamActionResponse_<ContainerAllocator> Type;

  SlamActionResponse_()
    : result(0)  {
    }
  SlamActionResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::hj_interface::SlamActionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::SlamActionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SlamActionResponse_

typedef ::hj_interface::SlamActionResponse_<std::allocator<void> > SlamActionResponse;

typedef boost::shared_ptr< ::hj_interface::SlamActionResponse > SlamActionResponsePtr;
typedef boost::shared_ptr< ::hj_interface::SlamActionResponse const> SlamActionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::SlamActionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::SlamActionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::SlamActionResponse_<ContainerAllocator1> & lhs, const ::hj_interface::SlamActionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::SlamActionResponse_<ContainerAllocator1> & lhs, const ::hj_interface::SlamActionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::SlamActionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::SlamActionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::SlamActionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::SlamActionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::SlamActionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::SlamActionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::SlamActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25458147911545c320c4c0a299eff763";
  }

  static const char* value(const ::hj_interface::SlamActionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25458147911545c3ULL;
  static const uint64_t static_value2 = 0x20c4c0a299eff763ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::SlamActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/SlamActionResponse";
  }

  static const char* value(const ::hj_interface::SlamActionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::SlamActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint8 result   # 0: 收到 \n"
"               # 1: slam待机 2: slam建图中 3: slam定位中 \n"
;
  }

  static const char* value(const ::hj_interface::SlamActionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::SlamActionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SlamActionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::SlamActionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::SlamActionResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_SLAMACTIONRESPONSE_H
