uint8  type        # 气囊控制类型 0: 查询气囊控制状态 1:充气 2:放气
uint16 stime       # 充放气自定义微调时间，微调不记录充放气状态 默认为0，取业务定义值，如有微调充放气 更新此字段
---
uint8 result       # 0 成功 -1 失败
uint8 status       # 1 充气中 2 放气中 3 充气结束 4 放气结束
# uint8 asorb_status # 0 吸空气 1 吸水
