// Generated by gencpp from file hj_interface/DownRay.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_DOWNRAY_H
#define HJ_INTERFACE_MESSAGE_DOWNRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct DownRay_
{
  typedef DownRay_<ContainerAllocator> Type;

  DownRay_()
    : timestamp()
    , left_down(0)
    , right_down(0)  {
    }
  DownRay_(const ContainerAllocator& _alloc)
    : timestamp()
    , left_down(0)
    , right_down(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _left_down_type;
  _left_down_type left_down;

   typedef uint8_t _right_down_type;
  _right_down_type right_down;





  typedef boost::shared_ptr< ::hj_interface::DownRay_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::DownRay_<ContainerAllocator> const> ConstPtr;

}; // struct DownRay_

typedef ::hj_interface::DownRay_<std::allocator<void> > DownRay;

typedef boost::shared_ptr< ::hj_interface::DownRay > DownRayPtr;
typedef boost::shared_ptr< ::hj_interface::DownRay const> DownRayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::DownRay_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::DownRay_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::DownRay_<ContainerAllocator1> & lhs, const ::hj_interface::DownRay_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.left_down == rhs.left_down &&
    lhs.right_down == rhs.right_down;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::DownRay_<ContainerAllocator1> & lhs, const ::hj_interface::DownRay_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::DownRay_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::DownRay_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::DownRay_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::DownRay_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::DownRay_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::DownRay_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::DownRay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2128dbaa01dbb390920d49a2d6291353";
  }

  static const char* value(const ::hj_interface::DownRay_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2128dbaa01dbb390ULL;
  static const uint64_t static_value2 = 0x920d49a2d6291353ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::DownRay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/DownRay";
  }

  static const char* value(const ::hj_interface::DownRay_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::DownRay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp\n"
"uint8 left_down   #!< 左下视红外， 0: 有遮挡, 1: 无遮挡.\n"
"uint8 right_down  #!< 右下视红外， 0: 有遮挡, 1: 无遮挡.\n"
;
  }

  static const char* value(const ::hj_interface::DownRay_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::DownRay_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.left_down);
      stream.next(m.right_down);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DownRay_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::DownRay_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::DownRay_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "left_down: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_down);
    s << indent << "right_down: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_down);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_DOWNRAY_H
