// Generated by gencpp from file hj_interface/DustPlugDetection.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_DUSTPLUGDETECTION_H
#define HJ_INTERFACE_MESSAGE_DUSTPLUGDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct DustPlugDetection_
{
  typedef DustPlugDetection_<ContainerAllocator> Type;

  DustPlugDetection_()
    : timestamp()
    , status1(0)
    , status2(0)  {
    }
  DustPlugDetection_(const ContainerAllocator& _alloc)
    : timestamp()
    , status1(0)
    , status2(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _status1_type;
  _status1_type status1;

   typedef uint8_t _status2_type;
  _status2_type status2;





  typedef boost::shared_ptr< ::hj_interface::DustPlugDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::DustPlugDetection_<ContainerAllocator> const> ConstPtr;

}; // struct DustPlugDetection_

typedef ::hj_interface::DustPlugDetection_<std::allocator<void> > DustPlugDetection;

typedef boost::shared_ptr< ::hj_interface::DustPlugDetection > DustPlugDetectionPtr;
typedef boost::shared_ptr< ::hj_interface::DustPlugDetection const> DustPlugDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::DustPlugDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::DustPlugDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::DustPlugDetection_<ContainerAllocator1> & lhs, const ::hj_interface::DustPlugDetection_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.status1 == rhs.status1 &&
    lhs.status2 == rhs.status2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::DustPlugDetection_<ContainerAllocator1> & lhs, const ::hj_interface::DustPlugDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::DustPlugDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::DustPlugDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::DustPlugDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::DustPlugDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::DustPlugDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::DustPlugDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::DustPlugDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f4934b1cc3cb876d383c428f514b142";
  }

  static const char* value(const ::hj_interface::DustPlugDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f4934b1cc3cb876ULL;
  static const uint64_t static_value2 = 0xd383c428f514b142ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::DustPlugDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/DustPlugDetection";
  }

  static const char* value(const ::hj_interface::DustPlugDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::DustPlugDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp\n"
"uint8 status1      #!<堵塞状态：[0x00]堵塞；[0x01]未堵塞\n"
"uint8 status2      #!<堵塞状态：[0x00]堵塞；[0x01]未堵塞\n"
;
  }

  static const char* value(const ::hj_interface::DustPlugDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::DustPlugDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.status1);
      stream.next(m.status2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DustPlugDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::DustPlugDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::DustPlugDetection_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "status1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status1);
    s << indent << "status2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_DUSTPLUGDETECTION_H
