// Generated by gencpp from file hj_interface/ErrorCodeStatisticResponse.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_ERRORCODESTATISTICRESPONSE_H
#define HJ_INTERFACE_MESSAGE_ERRORCODESTATISTICRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct ErrorCodeStatisticResponse_
{
  typedef ErrorCodeStatisticResponse_<ContainerAllocator> Type;

  ErrorCodeStatisticResponse_()
    : result(0)  {
    }
  ErrorCodeStatisticResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ErrorCodeStatisticResponse_

typedef ::hj_interface::ErrorCodeStatisticResponse_<std::allocator<void> > ErrorCodeStatisticResponse;

typedef boost::shared_ptr< ::hj_interface::ErrorCodeStatisticResponse > ErrorCodeStatisticResponsePtr;
typedef boost::shared_ptr< ::hj_interface::ErrorCodeStatisticResponse const> ErrorCodeStatisticResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator1> & lhs, const ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator1> & lhs, const ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13d5d28ceaaadbc975dd072a2e10b88a";
  }

  static const char* value(const ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13d5d28ceaaadbc9ULL;
  static const uint64_t static_value2 = 0x75dd072a2e10b88aULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/ErrorCodeStatisticResponse";
  }

  static const char* value(const ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint32 result        # 0: 收到  0~max：错误码个数\n"
"                            \n"
;
  }

  static const char* value(const ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ErrorCodeStatisticResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::ErrorCodeStatisticResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_ERRORCODESTATISTICRESPONSE_H
