// Generated by gencpp from file hj_interface/FlipCoverAck.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_FLIPCOVERACK_H
#define HJ_INTERFACE_MESSAGE_FLIPCOVERACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct FlipCoverAck_
{
  typedef FlipCoverAck_<ContainerAllocator> Type;

  FlipCoverAck_()
    : dstpos(0)
    , rst(0)  {
    }
  FlipCoverAck_(const ContainerAllocator& _alloc)
    : dstpos(0)
    , rst(0)  {
  (void)_alloc;
    }



   typedef int16_t _dstpos_type;
  _dstpos_type dstpos;

   typedef uint8_t _rst_type;
  _rst_type rst;





  typedef boost::shared_ptr< ::hj_interface::FlipCoverAck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::FlipCoverAck_<ContainerAllocator> const> ConstPtr;

}; // struct FlipCoverAck_

typedef ::hj_interface::FlipCoverAck_<std::allocator<void> > FlipCoverAck;

typedef boost::shared_ptr< ::hj_interface::FlipCoverAck > FlipCoverAckPtr;
typedef boost::shared_ptr< ::hj_interface::FlipCoverAck const> FlipCoverAckConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::FlipCoverAck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::FlipCoverAck_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::FlipCoverAck_<ContainerAllocator1> & lhs, const ::hj_interface::FlipCoverAck_<ContainerAllocator2> & rhs)
{
  return lhs.dstpos == rhs.dstpos &&
    lhs.rst == rhs.rst;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::FlipCoverAck_<ContainerAllocator1> & lhs, const ::hj_interface::FlipCoverAck_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::FlipCoverAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::FlipCoverAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::FlipCoverAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::FlipCoverAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::FlipCoverAck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::FlipCoverAck_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::FlipCoverAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac23e2cab9140d8ce4391cbd796aeffb";
  }

  static const char* value(const ::hj_interface::FlipCoverAck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac23e2cab9140d8cULL;
  static const uint64_t static_value2 = 0xe4391cbd796aeffbULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::FlipCoverAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/FlipCoverAck";
  }

  static const char* value(const ::hj_interface::FlipCoverAck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::FlipCoverAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 dstpos\n"
"uint8 rst\n"
;
  }

  static const char* value(const ::hj_interface::FlipCoverAck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::FlipCoverAck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dstpos);
      stream.next(m.rst);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlipCoverAck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::FlipCoverAck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::FlipCoverAck_<ContainerAllocator>& v)
  {
    s << indent << "dstpos: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dstpos);
    s << indent << "rst: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rst);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_FLIPCOVERACK_H
