// Generated by gencpp from file hj_interface/IotShadowRequest.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_IOTSHADOWREQUEST_H
#define HJ_INTERFACE_MESSAGE_IOTSHADOWREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hj_interface/AppData.h>

namespace hj_interface
{
template <class ContainerAllocator>
struct IotShadowRequest_
{
  typedef IotShadowRequest_<ContainerAllocator> Type;

  IotShadowRequest_()
    : appdata()  {
    }
  IotShadowRequest_(const ContainerAllocator& _alloc)
    : appdata(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::hj_interface::AppData_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::hj_interface::AppData_<ContainerAllocator> >> _appdata_type;
  _appdata_type appdata;





  typedef boost::shared_ptr< ::hj_interface::IotShadowRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::IotShadowRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IotShadowRequest_

typedef ::hj_interface::IotShadowRequest_<std::allocator<void> > IotShadowRequest;

typedef boost::shared_ptr< ::hj_interface::IotShadowRequest > IotShadowRequestPtr;
typedef boost::shared_ptr< ::hj_interface::IotShadowRequest const> IotShadowRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::IotShadowRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::IotShadowRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::IotShadowRequest_<ContainerAllocator1> & lhs, const ::hj_interface::IotShadowRequest_<ContainerAllocator2> & rhs)
{
  return lhs.appdata == rhs.appdata;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::IotShadowRequest_<ContainerAllocator1> & lhs, const ::hj_interface::IotShadowRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::IotShadowRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::IotShadowRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::IotShadowRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::IotShadowRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::IotShadowRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::IotShadowRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::IotShadowRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82be010920876fb28c00272bfa118dc0";
  }

  static const char* value(const ::hj_interface::IotShadowRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82be010920876fb2ULL;
  static const uint64_t static_value2 = 0x8c00272bfa118dc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::IotShadowRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/IotShadowRequest";
  }

  static const char* value(const ::hj_interface::IotShadowRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::IotShadowRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/AppData[] appdata\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hj_interface/AppData\n"
"string key\n"
"string payload\n"
"int8  res    	#response code\n"
"\n"
;
  }

  static const char* value(const ::hj_interface::IotShadowRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::IotShadowRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.appdata);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IotShadowRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::IotShadowRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::IotShadowRequest_<ContainerAllocator>& v)
  {
    s << indent << "appdata[]" << std::endl;
    for (size_t i = 0; i < v.appdata.size(); ++i)
    {
      s << indent << "  appdata[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hj_interface::AppData_<ContainerAllocator> >::stream(s, indent + "    ", v.appdata[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_IOTSHADOWREQUEST_H
