// Generated by gencpp from file hj_interface/RelocalizationResult.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_RELOCALIZATIONRESULT_H
#define HJ_INTERFACE_MESSAGE_RELOCALIZATIONRESULT_H

#include <ros/service_traits.h>


#include <hj_interface/RelocalizationResultRequest.h>
#include <hj_interface/RelocalizationResultResponse.h>


namespace hj_interface
{

struct RelocalizationResult
{

typedef RelocalizationResultRequest Request;
typedef RelocalizationResultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelocalizationResult
} // namespace hj_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hj_interface::RelocalizationResult > {
  static const char* value()
  {
    return "ce70405f9e402db3c9c35e66b3d437b4";
  }

  static const char* value(const ::hj_interface::RelocalizationResult&) { return value(); }
};

template<>
struct DataType< ::hj_interface::RelocalizationResult > {
  static const char* value()
  {
    return "hj_interface/RelocalizationResult";
  }

  static const char* value(const ::hj_interface::RelocalizationResult&) { return value(); }
};


// service_traits::MD5Sum< ::hj_interface::RelocalizationResultRequest> should match
// service_traits::MD5Sum< ::hj_interface::RelocalizationResult >
template<>
struct MD5Sum< ::hj_interface::RelocalizationResultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hj_interface::RelocalizationResult >::value();
  }
  static const char* value(const ::hj_interface::RelocalizationResultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hj_interface::RelocalizationResultRequest> should match
// service_traits::DataType< ::hj_interface::RelocalizationResult >
template<>
struct DataType< ::hj_interface::RelocalizationResultRequest>
{
  static const char* value()
  {
    return DataType< ::hj_interface::RelocalizationResult >::value();
  }
  static const char* value(const ::hj_interface::RelocalizationResultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hj_interface::RelocalizationResultResponse> should match
// service_traits::MD5Sum< ::hj_interface::RelocalizationResult >
template<>
struct MD5Sum< ::hj_interface::RelocalizationResultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hj_interface::RelocalizationResult >::value();
  }
  static const char* value(const ::hj_interface::RelocalizationResultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hj_interface::RelocalizationResultResponse> should match
// service_traits::DataType< ::hj_interface::RelocalizationResult >
template<>
struct DataType< ::hj_interface::RelocalizationResultResponse>
{
  static const char* value()
  {
    return DataType< ::hj_interface::RelocalizationResult >::value();
  }
  static const char* value(const ::hj_interface::RelocalizationResultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_RELOCALIZATIONRESULT_H
