// Generated by gencpp from file hj_interface/CollectBroadcast.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_COLLECTBROADCAST_H
#define HJ_INTERFACE_MESSAGE_COLLECTBROADCAST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct CollectBroadcast_
{
  typedef CollectBroadcast_<ContainerAllocator> Type;

  CollectBroadcast_()
    : action(0)
    , function(0)
    , ack(0)  {
    }
  CollectBroadcast_(const ContainerAllocator& _alloc)
    : action(0)
    , function(0)
    , ack(0)  {
  (void)_alloc;
    }



   typedef uint8_t _action_type;
  _action_type action;

   typedef uint8_t _function_type;
  _function_type function;

   typedef uint8_t _ack_type;
  _ack_type ack;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SYS_ACTION_SHUTDOWN)
  #undef SYS_ACTION_SHUTDOWN
#endif
#if defined(_WIN32) && defined(SYS_ACTION_RESET)
  #undef SYS_ACTION_RESET
#endif
#if defined(_WIN32) && defined(SYS_ACTION_RESTORE_FACTORY)
  #undef SYS_ACTION_RESTORE_FACTORY
#endif
#if defined(_WIN32) && defined(SYS_ACTION_SLEEP)
  #undef SYS_ACTION_SLEEP
#endif

  enum {
    SYS_ACTION_SHUTDOWN = 0u,
    SYS_ACTION_RESET = 1u,
    SYS_ACTION_RESTORE_FACTORY = 2u,
    SYS_ACTION_SLEEP = 3u,
  };


  typedef boost::shared_ptr< ::hj_interface::CollectBroadcast_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::CollectBroadcast_<ContainerAllocator> const> ConstPtr;

}; // struct CollectBroadcast_

typedef ::hj_interface::CollectBroadcast_<std::allocator<void> > CollectBroadcast;

typedef boost::shared_ptr< ::hj_interface::CollectBroadcast > CollectBroadcastPtr;
typedef boost::shared_ptr< ::hj_interface::CollectBroadcast const> CollectBroadcastConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::CollectBroadcast_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::CollectBroadcast_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::CollectBroadcast_<ContainerAllocator1> & lhs, const ::hj_interface::CollectBroadcast_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.function == rhs.function &&
    lhs.ack == rhs.ack;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::CollectBroadcast_<ContainerAllocator1> & lhs, const ::hj_interface::CollectBroadcast_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::CollectBroadcast_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::CollectBroadcast_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::CollectBroadcast_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::CollectBroadcast_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::CollectBroadcast_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::CollectBroadcast_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::CollectBroadcast_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67cc0c7e2ac7bf78445a63263d35291c";
  }

  static const char* value(const ::hj_interface::CollectBroadcast_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67cc0c7e2ac7bf78ULL;
  static const uint64_t static_value2 = 0x445a63263d35291cULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::CollectBroadcast_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/CollectBroadcast";
  }

  static const char* value(const ::hj_interface::CollectBroadcast_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::CollectBroadcast_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 action    # action type: see enum SYS_ACTION_* [references SysAction.msg]\n"
"uint8 function  # function type\n"
"uint8 ack  # 1: action oK, 0: action failed\n"
"uint8 SYS_ACTION_SHUTDOWN = 0\n"
"uint8 SYS_ACTION_RESET = 1      # reset from remote control\n"
"uint8 SYS_ACTION_RESTORE_FACTORY = 2    # restore factory from key\n"
"uint8 SYS_ACTION_SLEEP = 3\n"
"\n"
;
  }

  static const char* value(const ::hj_interface::CollectBroadcast_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::CollectBroadcast_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.function);
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CollectBroadcast_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::CollectBroadcast_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::CollectBroadcast_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
    s << indent << "function: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.function);
    s << indent << "ack: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_COLLECTBROADCAST_H
