// Generated by gencpp from file hj_interface/DockSignal.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_DOCKSIGNAL_H
#define HJ_INTERFACE_MESSAGE_DOCKSIGNAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct DockSignal_
{
  typedef DockSignal_<ContainerAllocator> Type;

  DockSignal_()
    : timestamp()
    , signal_1(0)
    , id(0)  {
    }
  DockSignal_(const ContainerAllocator& _alloc)
    : timestamp()
    , signal_1(0)
    , id(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef uint32_t _signal_1_type;
  _signal_1_type signal_1;

   typedef uint8_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::hj_interface::DockSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::DockSignal_<ContainerAllocator> const> ConstPtr;

}; // struct DockSignal_

typedef ::hj_interface::DockSignal_<std::allocator<void> > DockSignal;

typedef boost::shared_ptr< ::hj_interface::DockSignal > DockSignalPtr;
typedef boost::shared_ptr< ::hj_interface::DockSignal const> DockSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::DockSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::DockSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::DockSignal_<ContainerAllocator1> & lhs, const ::hj_interface::DockSignal_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.signal_1 == rhs.signal_1 &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::DockSignal_<ContainerAllocator1> & lhs, const ::hj_interface::DockSignal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::DockSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::DockSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::DockSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::DockSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::DockSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::DockSignal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::DockSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c16abf8c48c98eb93858486c67d80c62";
  }

  static const char* value(const ::hj_interface::DockSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc16abf8c48c98eb9ULL;
  static const uint64_t static_value2 = 0x3858486c67d80c62ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::DockSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/DockSignal";
  }

  static const char* value(const ::hj_interface::DockSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::DockSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp \n"
"uint32 signal_1\n"
"uint8 id #!< 基站检测超声波id\n"
;
  }

  static const char* value(const ::hj_interface::DockSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::DockSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.signal_1);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::DockSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::DockSignal_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "signal_1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.signal_1);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_DOCKSIGNAL_H
