// Generated by gencpp from file hj_interface/SlamAction.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_SLAMACTION_H
#define HJ_INTERFACE_MESSAGE_SLAMACTION_H

#include <ros/service_traits.h>


#include <hj_interface/SlamActionRequest.h>
#include <hj_interface/SlamActionResponse.h>


namespace hj_interface
{

struct SlamAction
{

typedef SlamActionRequest Request;
typedef SlamActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlamAction
} // namespace hj_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hj_interface::SlamAction > {
  static const char* value()
  {
    return "8560f3cd7c790209a64462aa6166d209";
  }

  static const char* value(const ::hj_interface::SlamAction&) { return value(); }
};

template<>
struct DataType< ::hj_interface::SlamAction > {
  static const char* value()
  {
    return "hj_interface/SlamAction";
  }

  static const char* value(const ::hj_interface::SlamAction&) { return value(); }
};


// service_traits::MD5Sum< ::hj_interface::SlamActionRequest> should match
// service_traits::MD5Sum< ::hj_interface::SlamAction >
template<>
struct MD5Sum< ::hj_interface::SlamActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hj_interface::SlamAction >::value();
  }
  static const char* value(const ::hj_interface::SlamActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hj_interface::SlamActionRequest> should match
// service_traits::DataType< ::hj_interface::SlamAction >
template<>
struct DataType< ::hj_interface::SlamActionRequest>
{
  static const char* value()
  {
    return DataType< ::hj_interface::SlamAction >::value();
  }
  static const char* value(const ::hj_interface::SlamActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hj_interface::SlamActionResponse> should match
// service_traits::MD5Sum< ::hj_interface::SlamAction >
template<>
struct MD5Sum< ::hj_interface::SlamActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hj_interface::SlamAction >::value();
  }
  static const char* value(const ::hj_interface::SlamActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hj_interface::SlamActionResponse> should match
// service_traits::DataType< ::hj_interface::SlamAction >
template<>
struct DataType< ::hj_interface::SlamActionResponse>
{
  static const char* value()
  {
    return DataType< ::hj_interface::SlamAction >::value();
  }
  static const char* value(const ::hj_interface::SlamActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_SLAMACTION_H
