// Generated by gencpp from file hj_interface/subPackData.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_SUBPACKDATA_H
#define HJ_INTERFACE_MESSAGE_SUBPACKDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct subPackData_
{
  typedef subPackData_<ContainerAllocator> Type;

  subPackData_()
    : addr()
    , ver()  {
    }
  subPackData_(const ContainerAllocator& _alloc)
    : addr(_alloc)
    , ver(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _addr_type;
  _addr_type addr;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ver_type;
  _ver_type ver;





  typedef boost::shared_ptr< ::hj_interface::subPackData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::subPackData_<ContainerAllocator> const> ConstPtr;

}; // struct subPackData_

typedef ::hj_interface::subPackData_<std::allocator<void> > subPackData;

typedef boost::shared_ptr< ::hj_interface::subPackData > subPackDataPtr;
typedef boost::shared_ptr< ::hj_interface::subPackData const> subPackDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::subPackData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::subPackData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::subPackData_<ContainerAllocator1> & lhs, const ::hj_interface::subPackData_<ContainerAllocator2> & rhs)
{
  return lhs.addr == rhs.addr &&
    lhs.ver == rhs.ver;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::subPackData_<ContainerAllocator1> & lhs, const ::hj_interface::subPackData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::subPackData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::subPackData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::subPackData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::subPackData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::subPackData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::subPackData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::subPackData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99201b5c87daec2355d50b09dd1d1bf5";
  }

  static const char* value(const ::hj_interface::subPackData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99201b5c87daec23ULL;
  static const uint64_t static_value2 = 0x55d50b09dd1d1bf5ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::subPackData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/subPackData";
  }

  static const char* value(const ::hj_interface::subPackData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::subPackData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string addr # 子固件包的存放位置\n"
"string ver  # 子固件包的版本号\n"
;
  }

  static const char* value(const ::hj_interface::subPackData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::subPackData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.addr);
      stream.next(m.ver);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct subPackData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::subPackData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::subPackData_<ContainerAllocator>& v)
  {
    s << indent << "addr: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.addr);
    s << indent << "ver: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ver);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_SUBPACKDATA_H
