// Generated by gencpp from file hj_interface/TripleUltra.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_TRIPLEULTRA_H
#define HJ_INTERFACE_MESSAGE_TRIPLEULTRA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct TripleUltra_
{
  typedef TripleUltra_<ContainerAllocator> Type;

  TripleUltra_()
    : timestamp()
    , front_l(0)
    , front_m(0)
    , front_r(0)
    , status(0)  {
    }
  TripleUltra_(const ContainerAllocator& _alloc)
    : timestamp()
    , front_l(0)
    , front_m(0)
    , front_r(0)
    , status(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef uint32_t _front_l_type;
  _front_l_type front_l;

   typedef uint32_t _front_m_type;
  _front_m_type front_m;

   typedef uint32_t _front_r_type;
  _front_r_type front_r;

   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::hj_interface::TripleUltra_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::TripleUltra_<ContainerAllocator> const> ConstPtr;

}; // struct TripleUltra_

typedef ::hj_interface::TripleUltra_<std::allocator<void> > TripleUltra;

typedef boost::shared_ptr< ::hj_interface::TripleUltra > TripleUltraPtr;
typedef boost::shared_ptr< ::hj_interface::TripleUltra const> TripleUltraConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::TripleUltra_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::TripleUltra_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::TripleUltra_<ContainerAllocator1> & lhs, const ::hj_interface::TripleUltra_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.front_l == rhs.front_l &&
    lhs.front_m == rhs.front_m &&
    lhs.front_r == rhs.front_r &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::TripleUltra_<ContainerAllocator1> & lhs, const ::hj_interface::TripleUltra_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::TripleUltra_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::TripleUltra_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::TripleUltra_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::TripleUltra_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::TripleUltra_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::TripleUltra_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::TripleUltra_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b376b7b40c7eabd0a1f0b34446bac0d";
  }

  static const char* value(const ::hj_interface::TripleUltra_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b376b7b40c7eabdULL;
  static const uint64_t static_value2 = 0x0a1f0b34446bac0dULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::TripleUltra_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/TripleUltra";
  }

  static const char* value(const ::hj_interface::TripleUltra_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::TripleUltra_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp \n"
"uint32 front_l  #!< 超声波左侧距离,单位:mm.\n"
"uint32 front_m  #!< 超声波中间侧距离,单位:mm.\n"
"uint32 front_r  #!< 超声波右侧距离,单位:mm.\n"
"uint8 status #!< 超声波状态,0 means normal,1 means error.\n"
;
  }

  static const char* value(const ::hj_interface::TripleUltra_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::TripleUltra_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.front_l);
      stream.next(m.front_m);
      stream.next(m.front_r);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TripleUltra_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::TripleUltra_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::TripleUltra_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "front_l: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.front_l);
    s << indent << "front_m: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.front_m);
    s << indent << "front_r: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.front_r);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_TRIPLEULTRA_H
