// Generated by gencpp from file hj_interface/TurbineMotor.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_TURBINEMOTOR_H
#define HJ_INTERFACE_MESSAGE_TURBINEMOTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct TurbineMotor_
{
  typedef TurbineMotor_<ContainerAllocator> Type;

  TurbineMotor_()
    : timestamp()
    , motor_ctl(0)
    , motor(0)  {
    }
  TurbineMotor_(const ContainerAllocator& _alloc)
    : timestamp()
    , motor_ctl(0)
    , motor(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _motor_ctl_type;
  _motor_ctl_type motor_ctl;

   typedef uint8_t _motor_type;
  _motor_type motor;





  typedef boost::shared_ptr< ::hj_interface::TurbineMotor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::TurbineMotor_<ContainerAllocator> const> ConstPtr;

}; // struct TurbineMotor_

typedef ::hj_interface::TurbineMotor_<std::allocator<void> > TurbineMotor;

typedef boost::shared_ptr< ::hj_interface::TurbineMotor > TurbineMotorPtr;
typedef boost::shared_ptr< ::hj_interface::TurbineMotor const> TurbineMotorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::TurbineMotor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::TurbineMotor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::TurbineMotor_<ContainerAllocator1> & lhs, const ::hj_interface::TurbineMotor_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.motor_ctl == rhs.motor_ctl &&
    lhs.motor == rhs.motor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::TurbineMotor_<ContainerAllocator1> & lhs, const ::hj_interface::TurbineMotor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::TurbineMotor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::TurbineMotor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::TurbineMotor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::TurbineMotor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::TurbineMotor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::TurbineMotor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::TurbineMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f8b164438161bddc0a3c30fee23c256";
  }

  static const char* value(const ::hj_interface::TurbineMotor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f8b164438161bddULL;
  static const uint64_t static_value2 = 0xc0a3c30fee23c256ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::TurbineMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/TurbineMotor";
  }

  static const char* value(const ::hj_interface::TurbineMotor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::TurbineMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp\n"
"uint8 motor_ctl     #!< 0 刹车； 1 运动；\n"
"uint8 motor        #!< 涡轮电机， 0，100>\n"
;
  }

  static const char* value(const ::hj_interface::TurbineMotor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::TurbineMotor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.motor_ctl);
      stream.next(m.motor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurbineMotor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::TurbineMotor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::TurbineMotor_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "motor_ctl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor_ctl);
    s << indent << "motor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_TURBINEMOTOR_H
