// Generated by gencpp from file hj_interface/WifiSet.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_WIFISET_H
#define HJ_INTERFACE_MESSAGE_WIFISET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct WifiSet_
{
  typedef WifiSet_<ContainerAllocator> Type;

  WifiSet_()
    : ssid()
    , passwd()  {
    }
  WifiSet_(const ContainerAllocator& _alloc)
    : ssid(_alloc)
    , passwd(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ssid_type;
  _ssid_type ssid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _passwd_type;
  _passwd_type passwd;





  typedef boost::shared_ptr< ::hj_interface::WifiSet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::WifiSet_<ContainerAllocator> const> ConstPtr;

}; // struct WifiSet_

typedef ::hj_interface::WifiSet_<std::allocator<void> > WifiSet;

typedef boost::shared_ptr< ::hj_interface::WifiSet > WifiSetPtr;
typedef boost::shared_ptr< ::hj_interface::WifiSet const> WifiSetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::WifiSet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::WifiSet_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::WifiSet_<ContainerAllocator1> & lhs, const ::hj_interface::WifiSet_<ContainerAllocator2> & rhs)
{
  return lhs.ssid == rhs.ssid &&
    lhs.passwd == rhs.passwd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::WifiSet_<ContainerAllocator1> & lhs, const ::hj_interface::WifiSet_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::WifiSet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::WifiSet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::WifiSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::WifiSet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::WifiSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::WifiSet_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::WifiSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a1acbdfb9626688c6de415b38657e58";
  }

  static const char* value(const ::hj_interface::WifiSet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a1acbdfb9626688ULL;
  static const uint64_t static_value2 = 0xc6de415b38657e58ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::WifiSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/WifiSet";
  }

  static const char* value(const ::hj_interface::WifiSet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::WifiSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ssid\n"
"string passwd\n"
;
  }

  static const char* value(const ::hj_interface::WifiSet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::WifiSet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ssid);
      stream.next(m.passwd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WifiSet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::WifiSet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::WifiSet_<ContainerAllocator>& v)
  {
    s << indent << "ssid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ssid);
    s << indent << "passwd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.passwd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_WIFISET_H
