// Generated by gencpp from file hj_interface/Fall.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_FALL_H
#define HJ_INTERFACE_MESSAGE_FALL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct Fall_
{
  typedef Fall_<ContainerAllocator> Type;

  Fall_()
    : timestamp()
    , left_down(0)
    , right_down(0)  {
    }
  Fall_(const ContainerAllocator& _alloc)
    : timestamp()
    , left_down(0)
    , right_down(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef uint32_t _left_down_type;
  _left_down_type left_down;

   typedef uint32_t _right_down_type;
  _right_down_type right_down;





  typedef boost::shared_ptr< ::hj_interface::Fall_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::Fall_<ContainerAllocator> const> ConstPtr;

}; // struct Fall_

typedef ::hj_interface::Fall_<std::allocator<void> > Fall;

typedef boost::shared_ptr< ::hj_interface::Fall > FallPtr;
typedef boost::shared_ptr< ::hj_interface::Fall const> FallConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::Fall_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::Fall_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::Fall_<ContainerAllocator1> & lhs, const ::hj_interface::Fall_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.left_down == rhs.left_down &&
    lhs.right_down == rhs.right_down;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::Fall_<ContainerAllocator1> & lhs, const ::hj_interface::Fall_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::Fall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::Fall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::Fall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::Fall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::Fall_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::Fall_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::Fall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7abfbe3ce80b05767c1fb0a5abedf5bb";
  }

  static const char* value(const ::hj_interface::Fall_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7abfbe3ce80b0576ULL;
  static const uint64_t static_value2 = 0x7c1fb0a5abedf5bbULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::Fall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/Fall";
  }

  static const char* value(const ::hj_interface::Fall_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::Fall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp\n"
"uint32 left_down\n"
"uint32 right_down\n"
;
  }

  static const char* value(const ::hj_interface::Fall_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::Fall_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.left_down);
      stream.next(m.right_down);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Fall_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::Fall_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::Fall_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "left_down: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.left_down);
    s << indent << "right_down: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.right_down);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_FALL_H
