// Generated by gencpp from file hj_interface/HealthCheckCode.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_HEALTHCHECKCODE_H
#define HJ_INTERFACE_MESSAGE_HEALTHCHECKCODE_H

#include <ros/service_traits.h>


#include <hj_interface/HealthCheckCodeRequest.h>
#include <hj_interface/HealthCheckCodeResponse.h>


namespace hj_interface
{

struct HealthCheckCode
{

typedef HealthCheckCodeRequest Request;
typedef HealthCheckCodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HealthCheckCode
} // namespace hj_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hj_interface::HealthCheckCode > {
  static const char* value()
  {
    return "4524ad5b6ec0b4e22059657941272d9a";
  }

  static const char* value(const ::hj_interface::HealthCheckCode&) { return value(); }
};

template<>
struct DataType< ::hj_interface::HealthCheckCode > {
  static const char* value()
  {
    return "hj_interface/HealthCheckCode";
  }

  static const char* value(const ::hj_interface::HealthCheckCode&) { return value(); }
};


// service_traits::MD5Sum< ::hj_interface::HealthCheckCodeRequest> should match
// service_traits::MD5Sum< ::hj_interface::HealthCheckCode >
template<>
struct MD5Sum< ::hj_interface::HealthCheckCodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hj_interface::HealthCheckCode >::value();
  }
  static const char* value(const ::hj_interface::HealthCheckCodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hj_interface::HealthCheckCodeRequest> should match
// service_traits::DataType< ::hj_interface::HealthCheckCode >
template<>
struct DataType< ::hj_interface::HealthCheckCodeRequest>
{
  static const char* value()
  {
    return DataType< ::hj_interface::HealthCheckCode >::value();
  }
  static const char* value(const ::hj_interface::HealthCheckCodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hj_interface::HealthCheckCodeResponse> should match
// service_traits::MD5Sum< ::hj_interface::HealthCheckCode >
template<>
struct MD5Sum< ::hj_interface::HealthCheckCodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hj_interface::HealthCheckCode >::value();
  }
  static const char* value(const ::hj_interface::HealthCheckCodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hj_interface::HealthCheckCodeResponse> should match
// service_traits::DataType< ::hj_interface::HealthCheckCode >
template<>
struct DataType< ::hj_interface::HealthCheckCodeResponse>
{
  static const char* value()
  {
    return DataType< ::hj_interface::HealthCheckCode >::value();
  }
  static const char* value(const ::hj_interface::HealthCheckCodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_HEALTHCHECKCODE_H
