// Generated by gencpp from file hj_interface/MagCalibActionRequest.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_MAGCALIBACTIONREQUEST_H
#define HJ_INTERFACE_MESSAGE_MAGCALIBACTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct MagCalibActionRequest_
{
  typedef MagCalibActionRequest_<ContainerAllocator> Type;

  MagCalibActionRequest_()
    : action(false)
    , duration(0)  {
    }
  MagCalibActionRequest_(const ContainerAllocator& _alloc)
    : action(false)
    , duration(0)  {
  (void)_alloc;
    }



   typedef uint8_t _action_type;
  _action_type action;

   typedef int32_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MagCalibActionRequest_

typedef ::hj_interface::MagCalibActionRequest_<std::allocator<void> > MagCalibActionRequest;

typedef boost::shared_ptr< ::hj_interface::MagCalibActionRequest > MagCalibActionRequestPtr;
typedef boost::shared_ptr< ::hj_interface::MagCalibActionRequest const> MagCalibActionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::MagCalibActionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::MagCalibActionRequest_<ContainerAllocator1> & lhs, const ::hj_interface::MagCalibActionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::MagCalibActionRequest_<ContainerAllocator1> & lhs, const ::hj_interface::MagCalibActionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c82bbd0c1634f2ce93958bc9ae1550d";
  }

  static const char* value(const ::hj_interface::MagCalibActionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c82bbd0c1634f2cULL;
  static const uint64_t static_value2 = 0xe93958bc9ae1550dULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/MagCalibActionRequest";
  }

  static const char* value(const ::hj_interface::MagCalibActionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool action # 0 无法标定 1 可以标定\n"
"int32 duration # 静止标定时间\n"
;
  }

  static const char* value(const ::hj_interface::MagCalibActionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagCalibActionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::MagCalibActionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::MagCalibActionRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
    s << indent << "duration: ";
    Printer<int32_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_MAGCALIBACTIONREQUEST_H
