// Generated by gencpp from file hj_interface/NaviAction.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_NAVIACTION_H
#define HJ_INTERFACE_MESSAGE_NAVIACTION_H

#include <ros/service_traits.h>


#include <hj_interface/NaviActionRequest.h>
#include <hj_interface/NaviActionResponse.h>


namespace hj_interface
{

struct NaviAction
{

typedef NaviActionRequest Request;
typedef NaviActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NaviAction
} // namespace hj_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hj_interface::NaviAction > {
  static const char* value()
  {
    return "96ee21f33d6725b3b74c864f9a1ad467";
  }

  static const char* value(const ::hj_interface::NaviAction&) { return value(); }
};

template<>
struct DataType< ::hj_interface::NaviAction > {
  static const char* value()
  {
    return "hj_interface/NaviAction";
  }

  static const char* value(const ::hj_interface::NaviAction&) { return value(); }
};


// service_traits::MD5Sum< ::hj_interface::NaviActionRequest> should match
// service_traits::MD5Sum< ::hj_interface::NaviAction >
template<>
struct MD5Sum< ::hj_interface::NaviActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hj_interface::NaviAction >::value();
  }
  static const char* value(const ::hj_interface::NaviActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hj_interface::NaviActionRequest> should match
// service_traits::DataType< ::hj_interface::NaviAction >
template<>
struct DataType< ::hj_interface::NaviActionRequest>
{
  static const char* value()
  {
    return DataType< ::hj_interface::NaviAction >::value();
  }
  static const char* value(const ::hj_interface::NaviActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hj_interface::NaviActionResponse> should match
// service_traits::MD5Sum< ::hj_interface::NaviAction >
template<>
struct MD5Sum< ::hj_interface::NaviActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hj_interface::NaviAction >::value();
  }
  static const char* value(const ::hj_interface::NaviActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hj_interface::NaviActionResponse> should match
// service_traits::DataType< ::hj_interface::NaviAction >
template<>
struct DataType< ::hj_interface::NaviActionResponse>
{
  static const char* value()
  {
    return DataType< ::hj_interface::NaviAction >::value();
  }
  static const char* value(const ::hj_interface::NaviActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_NAVIACTION_H
