// Generated by gencpp from file hj_interface/Ray.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_RAY_H
#define HJ_INTERFACE_MESSAGE_RAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hj_interface
{
template <class ContainerAllocator>
struct Ray_
{
  typedef Ray_<ContainerAllocator> Type;

  Ray_()
    : timestamp()
    , left_range(0.0)
    , front_range(0.0)  {
    }
  Ray_(const ContainerAllocator& _alloc)
    : timestamp()
    , left_range(0.0)
    , front_range(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef float _left_range_type;
  _left_range_type left_range;

   typedef float _front_range_type;
  _front_range_type front_range;





  typedef boost::shared_ptr< ::hj_interface::Ray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::Ray_<ContainerAllocator> const> ConstPtr;

}; // struct Ray_

typedef ::hj_interface::Ray_<std::allocator<void> > Ray;

typedef boost::shared_ptr< ::hj_interface::Ray > RayPtr;
typedef boost::shared_ptr< ::hj_interface::Ray const> RayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::Ray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::Ray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::Ray_<ContainerAllocator1> & lhs, const ::hj_interface::Ray_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.left_range == rhs.left_range &&
    lhs.front_range == rhs.front_range;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::Ray_<ContainerAllocator1> & lhs, const ::hj_interface::Ray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::Ray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::Ray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::Ray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::Ray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::Ray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::Ray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::Ray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8cf845e020f381f9c616bc033a10e989";
  }

  static const char* value(const ::hj_interface::Ray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8cf845e020f381f9ULL;
  static const uint64_t static_value2 = 0xc616bc033a10e989ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::Ray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/Ray";
  }

  static const char* value(const ::hj_interface::Ray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::Ray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp\n"
"float32 left_range    # !< 激光测距，左侧激光探测距离\n"
"float32 front_range   # !< 激光测距，前方激光探测距离，暂未使用\n"
;
  }

  static const char* value(const ::hj_interface::Ray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::Ray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.left_range);
      stream.next(m.front_range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::Ray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::Ray_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "left_range: ";
    Printer<float>::stream(s, indent + "  ", v.left_range);
    s << indent << "front_range: ";
    Printer<float>::stream(s, indent + "  ", v.front_range);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_RAY_H
