uint8 outwater_status         # 出水, 状态：[0x00] passed；[0x01] failed
uint8 outwater_hall_status    # 出水hall, 状态：[0x00] passed；[0x01] failed
uint8 outwater_hall_status2   # 出水hall2, 状态：[0x00] passed；[0x01] failed
uint8 dirtybox_hall_status    # 滤篮hall, 状态：[0x00] passed；[0x01] failed
uint8 ango_status             # 岸歌, 状态：[0x00] passed；[0x01] failed
uint8 left_ray_status         # 左下视, 状态：[0x00] passed；[0x01] failed
uint8 right_ray_status        # 右下视, 状态：[0x00] passed；[0x01] failed